// Generates the SQL that proves score.ts and the total_score generated column
// agree. Slice 1 spec §5.3.
//
// The expected totals come from the real totalScore(), imported straight from
// the TypeScript source -- Node strips the types on import, so there is no
// second copy of the arithmetic here to drift out of step with the first.
//
// The SQL side does not hard-code the expression either: it reads the live one
// out of pg_attrdef and evaluates it with dynamic SQL. So this checks what is
// deployed, not a copy of what was intended. Nothing is inserted and no
// sequence advances -- the expression is evaluated over a VALUES list.
//
// buildRows() and buildSql() are exported so tests/scoreParity.test.ts can
// check them without writing a file. The write happens only when this module is
// the entry point.
import { writeFileSync } from 'node:fs'

const { PILLARS, MAX_PILLAR_SCORE, totalScore } = await import('../src/lib/score.ts')

export const OUT = 'scripts/.score-parity.generated.sql'
export const CHUNK = 1000

// null as well as 1..5, because null propagation is the rule under test:
// "incomplete has no score" is enforced by the database through `+` returning
// null, and by totalScore() through an early return. Those are two different
// mechanisms reaching the same answer, which is exactly the kind of agreement
// worth checking rather than assuming.
const VALUES = [null, ...Array.from({ length: MAX_PILLAR_SCORE }, (_, i) => i + 1)]

function* combinations(depth = 0, partial = {}) {
  if (depth === PILLARS.length) {
    yield { ...partial }
    return
  }
  for (const value of VALUES) {
    yield* combinations(depth + 1, { ...partial, [PILLARS[depth]]: value })
  }
}

export function buildRows() {
  const rows = []
  for (const combination of combinations()) {
    const cells = PILLARS.map((pillar) =>
      combination[pillar] === null ? 'null::smallint' : `${combination[pillar]}::smallint`,
    )
    const expected = totalScore(combination)
    cells.push(expected === null ? 'null::smallint' : `${expected}::smallint`)
    rows.push(`(${cells.join(',')})`)
  }
  return rows
}

export function buildSql(rows = buildRows()) {
  const columns = [...PILLARS, 'expected'].join(', ')

  const chunks = []
  for (let start = 0; start < rows.length; start += CHUNK) {
    chunks.push(rows.slice(start, start + CHUNK))
  }

  const body = chunks
    .map(
      (chunk, index) => `
do $$
declare
  expression text;
  mismatches bigint;
begin
  -- The live expression, not a copy of it. If somebody alters the column, this
  -- picks up the alteration rather than checking yesterday's definition.
  select pg_get_expr(d.adbin, d.adrelid)
    into strict expression
    from pg_attrdef d
    join pg_attribute a on a.attrelid = d.adrelid and a.attnum = d.adnum
   where d.adrelid = 'public.checkins'::regclass
     and a.attname = 'total_score';

  execute format($fmt$
    select count(*) from (values %s) as v(${columns})
     where (%s) is distinct from expected
  $fmt$, $values$${chunk.join(',')}$values$, expression)
    into mismatches;

  if mismatches <> 0 then
    raise exception
      'score parity FAILED in chunk ${index + 1}: % of ${chunk.length} combinations disagree between score.ts and total_score',
      mismatches;
  end if;

  raise notice 'chunk ${index + 1}: ${chunk.length} combinations agree';
end $$;`,
    )
    .join('\n')

  const sql = `-- GENERATED by scripts/score-parity.mjs. Do not edit, and do not commit.
-- ${rows.length} pillar combinations, in ${chunks.length} chunks.
-- Every chunk raises an exception on the first disagreement, so a green run
-- means every combination agreed -- not that the file was empty.
${body}

do $$
begin
  raise notice 'score parity PASSED: all ${rows.length} combinations agree';
end $$;
`
  return { sql, chunkCount: chunks.length }
}

if (import.meta.main) {
  const rows = buildRows()
  const { sql, chunkCount } = buildSql(rows)
  writeFileSync(OUT, sql)
  console.log(`wrote ${OUT}: ${rows.length} combinations in ${chunkCount} chunks`)
}
