// Turns a local, gitignored list of client names into SQL that seeds
// public.clients. Slice 1 step 5.
//
// Why the names are not in this file, or any committed file. This repository is
// PUBLIC. A seed migration or a committed seed.sql holding the roster would put
// the agency's client list somewhere searchable, and would leave it in git
// history permanently even if a later commit removed it. So the names live in
// clients.local.txt, which is gitignored, and this script -- which is committed
// and reviewable -- never contains one.
//
// The generated SQL is idempotent, which matters more here than it looks:
// public.clients has NO unique constraint on name, so a plain INSERT run twice
// produces duplicate clients with no error. Every row is guarded by a
// `not exists` on the name instead.
//
// It also does not touch rows that already exist. If somebody pauses a client
// in the app, re-running this must not quietly set them back to active.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

export const IN = 'clients.local.txt'
export const OUT = 'scripts/.clients.generated.sql'

// Mirrors the check constraint on public.clients.status in
// supabase/migrations/20260821021840_create_clients_and_checkins.sql. There is
// no 'inactive' -- a client who leaves is 'former'.
export const STATUSES = ['active', 'paused', 'cancelled', 'former']

const MAX_NAME_LENGTH = 200

// Any C0 control character, plus DEL. Not a SQL-injection guard -- doubling the
// quote in quote() is what makes a literal safe, and it is sufficient on its
// own. This is a data-quality guard: a name pasted out of a spreadsheet can
// carry a tab or a stray control byte, which would then sit invisibly inside a
// client's name forever, matching nothing anybody later types. A newline cannot
// reach here, because parseRoster splits on newlines before it looks at a name.
// Written as a code-point scan rather than a regex character class: the class
// is what oxlint's no-control-regex flags, and a suppression comment would be a
// worse thing to leave behind than four lines of loop.
function hasControlCharacter(value) {
  for (const character of value) {
    const code = character.codePointAt(0)
    if (code < 0x20 || code === 0x7f) return true
  }
  return false
}

// Doubling the quote is the whole of SQL string escaping for a literal.
function quote(value) {
  return `'${value.replaceAll("'", "''")}'`
}

export function parseRoster(text) {
  const roster = []
  const seen = new Map()

  text.split(/\r?\n/).forEach((rawLine, index) => {
    const lineNumber = index + 1
    const line = rawLine.trim()
    if (line === '' || line.startsWith('#')) return

    const parts = line.split('|').map((part) => part.trim())
    if (parts.length > 2) {
      throw new Error(
        `${IN}:${lineNumber}: more than one '|' -- expected "Name" or "Name | status"`,
      )
    }

    const name = parts[0]
    if (name === '') throw new Error(`${IN}:${lineNumber}: a name is empty`)
    if (name.length > MAX_NAME_LENGTH) {
      throw new Error(`${IN}:${lineNumber}: name is longer than ${MAX_NAME_LENGTH} characters`)
    }
    if (hasControlCharacter(name)) {
      throw new Error(`${IN}:${lineNumber}: name contains a control character`)
    }

    const status = parts[1] === undefined || parts[1] === '' ? 'active' : parts[1]
    if (!STATUSES.includes(status)) {
      throw new Error(
        `${IN}:${lineNumber}: status ${JSON.stringify(status)} is not one of ${STATUSES.join(', ')}`,
      )
    }

    // A duplicate here is a typo in the input, not something to silently
    // collapse: the SQL is idempotent either way, so nothing downstream would
    // ever report it.
    const key = name.toLocaleLowerCase()
    if (seen.has(key)) {
      throw new Error(`${IN}:${lineNumber}: duplicate of line ${seen.get(key)}`)
    }
    seen.set(key, lineNumber)

    roster.push({ name, status })
  })

  if (roster.length === 0) {
    throw new Error(`${IN} holds no names. Refusing to generate SQL that would do nothing.`)
  }

  return roster
}

export function buildSql(roster) {
  const values = roster.map((c) => `    (${quote(c.name)}, ${quote(c.status)})`).join(',\n')
  const names = roster.map((c) => quote(c.name)).join(', ')

  return `-- GENERATED by scripts/seed-clients.mjs from ${IN}. Do not commit: this
-- repository is public and these are real client names.
--
-- ${roster.length} clients. Run it in the Supabase dashboard -> SQL Editor,
-- against the intended project. The editor runs with administrative rights, so
-- RLS is not consulted; that is expected for a seed and is why this is not a
-- CLI command.
--
-- Safe to run twice. public.clients has no unique constraint on name, so each
-- row is guarded by a \`not exists\` rather than \`on conflict\`. Rows that are
-- already there are left exactly as they are -- a client somebody paused in the
-- app does not get set back to active by a re-run.

do $$
declare
  inserted integer;
  present  integer;
begin
  insert into public.clients (name, status)
  select v.name, v.status
    from (values
${values}
    ) as v(name, status)
   where not exists (
     select 1 from public.clients c where c.name = v.name
   );

  get diagnostics inserted = row_count;

  select count(*) into present
    from public.clients c
   where c.name in (${names});

  -- Assert a positive expected count, so "inserted 0" cannot read as success
  -- when the reason is that nothing matched. The exception rolls the insert
  -- back, so a partial seed cannot survive.
  if present <> ${roster.length} then
    raise exception
      'seed-clients FAILED: expected % roster clients present after the insert, found %. Nothing was committed.',
      ${roster.length}, present;
  end if;

  raise notice 'seed-clients OK -- % inserted, % already present, % on the roster', inserted, present - inserted, present;
end $$;

-- The evidence, because a NOTICE is easy to miss in the SQL editor and
-- "Success. No rows returned" looks identical to having done nothing. Expect
-- ${roster.length} roster rows here, plus anything that was already in the table.
select id, name, status, created_at
  from public.clients
 order by name;
`
}

if (import.meta.main) {
  if (!existsSync(IN)) {
    console.error(
      `${IN} does not exist. Create it (it is gitignored) with one client per line:\n` +
        `\n  Some Client\n  Another Client | paused\n\n` +
        `Status is optional and defaults to active. One of: ${STATUSES.join(', ')}.`,
    )
    process.exit(1)
  }

  const roster = parseRoster(readFileSync(IN, 'utf8'))
  writeFileSync(OUT, buildSql(roster))

  // Counts only, never the names: this line ends up in terminal scrollback, CI
  // logs and agent transcripts.
  const byStatus = STATUSES.map(
    (s) => `${roster.filter((c) => c.status === s).length} ${s}`,
  ).join(', ')
  console.log(`wrote ${OUT}: ${roster.length} clients (${byStatus})`)
}
